version: "2.1"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-broker:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "names:1:1,greetings:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  statefun-manager:
    image: apache/flink-statefun:3.0.0-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      ROLE: master
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml

  statefun-worker:
    image: apache/flink-statefun:3.0.0-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - statefun-manager
      - kafka-broker
    links:
      - "statefun-manager:statefun-manager"
      - "kafka-broker:kafka-broker"
    environment:
      ROLE: worker
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/greeter/module.yaml


  haskell-worker:
    command: "./flink-statefulfun-greeter +RTS -N8"
    # Uncomment to build locally
    build:
      context: ..
      dockerfile: example/greeter/Dockerfile
    image: tdbgamer/flink-statefulfun-hs-greeter
    expose:
      - "8000"
    ports:
      - "5000:5000"

  event-generator:
    build:
      context: generator
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
